#
# VibeLinux pacman configuration
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Never
LocalFileSigLevel = Never
NoConfirm

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist


