#
# VibeLinux pacman configuration
#

[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Never
LocalFileSigLevel = Never
NoConfirm

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

# CachyOS repos (for q- calamares, only available when building on CachyOS)
[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist
